CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL PRIMARY KEY,
  openid VARCHAR(100) UNIQUE NOT NULL,
  nickname VARCHAR(100),
  avatar VARCHAR(255),
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS resume (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "user"(id),
  file_name VARCHAR(255),
  content TEXT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analysis_record (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES "user"(id),
  resume_id INTEGER NOT NULL REFERENCES resume(id),
  jd TEXT,
  result TEXT,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
